'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ResponsiveAppBar from './components/app-bar'
import { ThemeProvider } from '@mui/material/styles';

import theme from './theme';




// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
        <ThemeProvider theme={theme}>
          <div>
            <ResponsiveAppBar />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
